"""add v3 amm and token launchpad tables

Revision ID: 2628d089ba20
Revises: 7c1a9e2b3f4d
Create Date: 2026-07-06 06:07:42.853269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2628d089ba20'
down_revision: Union[str, None] = '7c1a9e2b3f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pools_v3',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token0', sa.String(length=20), nullable=False),
    sa.Column('token1', sa.String(length=20), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('tick_spacing', sa.Integer(), nullable=False),
    sa.Column('sqrt_price', sa.Numeric(precision=40, scale=20), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('liquidity', sa.Numeric(precision=40, scale=8), nullable=False),
    sa.Column('fee_growth_global_0', sa.Numeric(precision=40, scale=20), nullable=False),
    sa.Column('fee_growth_global_1', sa.Numeric(precision=40, scale=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token0', 'token1', 'fee', name='uq_pool_v3_pair_fee')
    )
    op.create_table('positions_v3',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tick_lower', sa.Integer(), nullable=False),
    sa.Column('tick_upper', sa.Integer(), nullable=False),
    sa.Column('liquidity', sa.Numeric(precision=40, scale=8), nullable=False),
    sa.Column('fee_growth_inside_0_last', sa.Numeric(precision=40, scale=20), nullable=False),
    sa.Column('fee_growth_inside_1_last', sa.Numeric(precision=40, scale=20), nullable=False),
    sa.Column('tokens_owed_0', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('tokens_owed_1', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools_v3.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'owner_id', 'tick_lower', 'tick_upper', name='uq_position_v3')
    )
    op.create_table('tick_bitmap',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('word_pos', sa.Integer(), nullable=False),
    sa.Column('bitmap', sa.String(length=66), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools_v3.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'word_pos', name='uq_tick_bitmap_pool_word')
    )
    op.create_table('tick_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('tick_index', sa.Integer(), nullable=False),
    sa.Column('liquidity_gross', sa.Numeric(precision=40, scale=8), nullable=False),
    sa.Column('liquidity_net', sa.Numeric(precision=40, scale=8), nullable=False),
    sa.Column('fee_growth_outside_0', sa.Numeric(precision=40, scale=20), nullable=False),
    sa.Column('fee_growth_outside_1', sa.Numeric(precision=40, scale=20), nullable=False),
    sa.Column('initialized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools_v3.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'tick_index', name='uq_tick_data_pool_tick')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_supply', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.alter_column('balances', 'available',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=30, scale=8),
               existing_nullable=False)
    op.alter_column('balances', 'locked',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=30, scale=8),
               existing_nullable=False)
    op.create_unique_constraint('uq_balance_user_currency', 'balances', ['user_id', 'currency'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_balance_user_currency', 'balances', type_='unique')
    op.alter_column('balances', 'locked',
               existing_type=sa.Numeric(precision=30, scale=8),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('balances', 'available',
               existing_type=sa.Numeric(precision=30, scale=8),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=False)
    op.drop_table('tokens')
    op.drop_table('tick_data')
    op.drop_table('tick_bitmap')
    op.drop_table('positions_v3')
    op.drop_table('pools_v3')
    # ### end Alembic commands ###
